### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by pythoninthegrass** [techlahoma/Hacktoberfest#3]
To make contributions to this repo consistent and clearly outline, a `CONTRIBUTING.md` file needs to be created (cf. [GitHub Docs](https://github.com/github/docs/blob/main/CONTRIBUTING.md)).

**Comment by geekthattweaks** [comment]
So I've started noodling on this. I've added the Techlahoma Code of Conduct but what else should be added?

**Comment by geekthattweaks** [comment]
I'm going to use [this](https://github.com/techlahoma/code-newbies/issues/2) as a template for what I'm shooting for.

**Comment by pythoninthegrass** [comment]
Don't have any strict requirements here. Maybe @kacollins has suggestions?

**Comment by pythoninthegrass** [comment]
Resolved via #13
