### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by pythoninthegrass** [techlahoma/Hacktoberfest#4]
A [license](https://github.com/github/docs/blob/0c22a4bcbdba9ddf482c130cf612d86b4dc6195e/content/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository.md), while optional, makes sure that any contributors or individuals who fork a repo understand how the content can be used.

My vote is for the [Unlicense](https://github.com/pythoninthegrass/python_template/blob/main/LICENSE.md).

**Comment by geekthattweaks** [comment]
I've always been a fan of CC but the Unlicense makes sense here to me!

**Comment by pythoninthegrass** [comment]
![Make it so](https://media.giphy.com/media/bKnEnd65zqxfq/giphy.gif)

**Comment by geekthattweaks** [comment]
Aye Aye Captain!

**Comment by pythoninthegrass** [comment]
Closed by #12
